# ===========================================
# Site Information Settings
# ===========================================

# Site creation time
since: 2017

# Custom your favicon.ico in `site/source`
favicon: /avatar.png

# display the logo
logo: true

# display blog title
title: false

auto_excerpt:
  enable: true
  length: 100

# ===========================================
# Menu Settings
# ===========================================
menu:
  Home: /
  Archives: /archives/
  # Tags: /tags
  # Categories: /categories
  About: /about

# ===========================================
# Theme Settings
# ===========================================
# theme styling
theme:
  toc: false
  fancybox: true

copyright:
  enable: true
  # https://creativecommons.org/
  license: '<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/" target="_blank">知识共享署名-非商业性使用 4.0 国际许可协议</a>'

reward:
  enable: false
  qrCode:
    wechat: images/reward/wechat.png
    alipay: images/reward/alipay.png

# ===========================================
# Third Party Services Settings
# ===========================================

# LeanCloud
leancloud:
  app_id:
  app_key:

# Baidu Analytics
baidu_analytics: 41c6fe4f66621dbc8a1f78c002656732
# Baidu Verification
baidu_verification: 

# Google Analytics
google_analytics:
# Google Verification
google_verification:

# Disqus
disqus_shortname: rekols

#Changyan
changyan:
  appid:
  appkey:

#LiveRe
livere_datauid:

# ===========================================
# Version
# ===========================================
version: 1.0
